name: gym_admin
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_svg: 1.1.0
  shared_preferences: 2.0.15
  intl: 0.17.0
  http: 0.13.4
  image_picker: ^0.8.5
  path: 1.8.1
  flutter_launcher_icons: 0.9.3



  cupertino_icons: ^1.0.2

dev_dependencies:


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/